const LIST_BOOKING_SERVICES = 'listBookingServices';
const GET_ALL_LIST_BOOKING_SERVICES = `${LIST_BOOKING_SERVICES}/getAllListBookingServices`;
const SAVE_ALL_LIST_BOOKING_SERVICES = `${LIST_BOOKING_SERVICES}/saveAllListBookingServices`;

export {
    GET_ALL_LIST_BOOKING_SERVICES,
    SAVE_ALL_LIST_BOOKING_SERVICES,
}
