const NOTIFICATION_SERVICES = 'notificationServices';
const GET_ALL_NOTIFICATION_SERVICES = `${NOTIFICATION_SERVICES}/getAllNotificationServices`;
const SAVE_ALL_NOTIFICATION_SERVICES = `${NOTIFICATION_SERVICES}/saveAllNotificationServices`;

export {
    GET_ALL_NOTIFICATION_SERVICES,
    SAVE_ALL_NOTIFICATION_SERVICES,
}
