const SYSTEM_SERVICES = 'systemServices';
const GET_ALL_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/getAllSystemServices`;
const SAVE_ALL_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/saveAllSystemServices`;

const CREATE_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/createSystemServices`;

const GET_DETAIL_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/getDetailSystemServices`;

const UPDATE_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/updateSystemServices`;

const DELETE_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/deleteSystemServices`;

const GET_RULES_SYSTEM_SERVICES = `${SYSTEM_SERVICES}/getRulesSystemServices`;

export {
    GET_ALL_SYSTEM_SERVICES,
    SAVE_ALL_SYSTEM_SERVICES,
    CREATE_SYSTEM_SERVICES,
    GET_DETAIL_SYSTEM_SERVICES,
    UPDATE_SYSTEM_SERVICES,
    DELETE_SYSTEM_SERVICES,
    GET_RULES_SYSTEM_SERVICES,
}
